apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-applicationset-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/mixxor/gitops-applicationset-example.git
    targetRevision: HEAD
    path: applications/dev-applicationset/
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  SyncPolicy:
    syncOptions:
    - CreateNamespace=true