apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

patches:
- path: replica-count.yaml

configMapGenerator:
- name: nginx-config
  files:
  - nginx.conf
